// AI Generated Code
//
// This implementation was generated by an AI assistant
// and is included for educational purposes.
//
// While the code is functional, it may not adhere to best practices
// or be optimized for performance. Users are encouraged to review,
// modify, and enhance the code as needed for their specific use cases.


package com.gabriel.utils;

import java.util.Random;

/**
 * Utility class for generating integer arrays used in tests and benchmarks.
 */
public final class RandomArrayGenerator {

    private static final Random RANDOM = new Random();

    private RandomArrayGenerator() {
        throw new AssertionError("Utility class");
    }

    /**
     * Generates an array with random values between 0 (inclusive) and
     * the array size (exclusive).
     *
     * @param size number of elements
     * @return randomly generated array
     * @throws IllegalArgumentException if size is negative
     */
    public static int[] generate(int size) {
        if (size < 0) {
            throw new IllegalArgumentException("Size cannot be negative");
        }

        return generate(size, 0, size);
    }

    /**
     * Generates an array with random values in the specified range.
     *
     * @param size number of elements
     * @param min minimum value (inclusive)
     * @param max maximum value (exclusive)
     * @return randomly generated array
     * @throws IllegalArgumentException if size is negative or min >= max
     */
    public static int[] generate(int size, int min, int max) {
        if (size < 0) {
            throw new IllegalArgumentException("Size cannot be negative");
        }

        if (min >= max) {
            throw new IllegalArgumentException("min must be less than max");
        }

        int[] array = new int[size];

        for (int i = 0; i < size; i++) {
            array[i] = RANDOM.nextInt(min, max);
        }

        return array;
    }

    /**
     * Generates a sorted array.
     *
     * @param size number of elements
     * @return sorted array
     * @throws IllegalArgumentException if size is negative
     */
    public static int[] generateSorted(int size) {
        if (size < 0) {
            throw new IllegalArgumentException("Size cannot be negative");
        }

        int[] array = new int[size];

        for (int i = 0; i < size; i++) {
            array[i] = i;
        }

        return array;
    }

    /**
     * Generates a reverse sorted array.
     *
     * @param size number of elements
     * @return reverse sorted array
     * @throws IllegalArgumentException if size is negative
     */
    public static int[] generateReverseSorted(int size) {
        if (size < 0) {
            throw new IllegalArgumentException("Size cannot be negative");
        }

        int[] array = new int[size];

        for (int i = 0; i < size; i++) {
            array[i] = size - i - 1;
        }

        return array;
    }

    /**
     * Generates a nearly sorted array.
     * A small number of random swaps are performed.
     *
     * @param size number of elements
     * @return nearly sorted array
     * @throws IllegalArgumentException if size is negative
     */
    public static int[] generateNearlySorted(int size) {
        int[] array = generateSorted(size);

        int swaps = Math.max(1, size / 20); // ~5% of the array

        for (int i = 0; i < swaps; i++) {
            int first = RANDOM.nextInt(size);
            int second = RANDOM.nextInt(size);

            int temp = array[first];
            array[first] = array[second];
            array[second] = temp;
        }

        return array;
    }
}